### PR TITLE
ci: changed TokenScreens' title from its label to its identifier

### PR DESCRIPTION
**Pull request by Shukriii**
# Changed TokenScreens' title from its label to its identifie

Made this change in hopes that the UI tests will start passing.

# Checklist

## Before raising your pull request:
- [x] Commit messages that conform to conventional commit messages
- [x] Ran the app locally ensuring it builds 
- [x] Ran the tests locally ensuring they pass on Build
- [x] Pull request has a clear title with a short description about the feature or update
- [x] Created a `draft` pull request if it is not yet ready for review

## Before your pull request can be reviewed:
~- [ ] Met all of the acceptance criteria specified in the user story on Jira~
- [x] Reviewed your own code to ensure you are following the style guidelines
- [x] Ran the app and tested the feature on a range of device sizes
      Please include iPod Touch, iPhone SE and iPhone 11 as a minimum.
~- [ ] Written Unit and Integration tests if needed~

~- [ ] Met all accessibility requirements?
    - [ ] Checked dynamic type sizes are applied
    - [ ] Checked VoiceOver can navigate your new code
    - [ ] Checked a user can navigate only using a keyboard around your new code~

## Before merging your pull request:
- [ ] Ensure that the code coverage and SonarCloud checks have passed
- [ ] Actioned and resolved all comments, reaching out to reviewers for clarifications if necessary.
- [ ] Ran the app to ensure that no regressions have been caused by changes during code review.

### CODE REVIEW

**Review by robinphillips — COMMENTED** [review]
It's great that this has worked. It would be good to identify which of these changes was the one that fixed it and revert the one that wasn't required. The benefit of that is that we then learn about what the actual fix was too :)

**Comment by robinphillips** [comment]
> It's great that this has worked. It would be good to identify which of these changes was the one that fixed it and revert the one that wasn't required. The benefit of that is that we then learn about what the actual fix was too :)

Ah, the runner is only doing Unit Tests on commit. I think it would be worth considering setting up some other workflows for manually testing UITests when required. It would need to be a separate ticket, but something to talk to Gabby and Dylan about.

**Review by mcgarj — APPROVED** [review]
Nice job!

**Review by robinphillips — APPROVED** [review]
Not sure if this approval will help with regards to merging, but good work tracking this down :)

**Pull request merged**
